version: 2
updates:
- package-ecosystem: cargo
  directory: "/rust"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/example"
  schedule:
    interval: daily
