on:
  push:
    branches:
      - main

jobs:
  benchmark_base_branch:
    name: Benchmark
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rust
    steps:
      - uses: actions/checkout@v4
      - uses: bencherdev/bencher@main
      - run: |
          bencher run \
          --project md5gen-wasm \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --branch main \
          --testbed ubuntu-latest \
          --github-actions '${{ secrets.GITHUB_TOKEN }}' \
          "cargo bench"