on:
  pull_request:
    branches:
      - main
name: PR Checks
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rust
    steps:
      - uses: actions/checkout@v4
      - name: Install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - run: cargo fmt --all --check 
      - run: cargo clippy --all-targets --all-features -- -D warnings
      - run: cargo test
      