
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
  id-token: write
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node
          token: ${{ steps.app-token.outputs.token }}
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
        if: ${{ steps.release.outputs.release_created }}
      - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
        if: ${{ steps.release.outputs.release_created }}
      - name: Install wasm-opt
        uses: baptiste0928/cargo-install@v3
        if: ${{ steps.release.outputs.release_created }}
        with:
          crate: wasm-opt
          version: '0.116.1'
      - run: wasm-pack build --target bundler
        working-directory: ${{ github.workspace }}/rust
        if: ${{ steps.release.outputs.release_created }}
      - run: wasm-opt -O3 -o md5_bg.wasm md5_bg.wasm
        working-directory: ${{ github.workspace }}/rust/pkg
        if: ${{ steps.release.outputs.release_created }}
      - run: npm install
        if: ${{ steps.release.outputs.release_created }}
      - run: npm run build
        if: ${{ steps.release.outputs.release_created }}
      - run: npm publish --provenance --access public
        if: ${{ steps.release.outputs.release_created }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
